# -*- coding: utf-8 -*-
"""Numpy_SlicingWithStep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 19: NumPy - Setting Values Using Indexing
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Setting specific values using indexing
array[[1, 3]] = [100, 200]

print('Array after Setting Values:', array)