# -*- coding: utf-8 -*-
"""Numpy_UniqueElementsAndCounting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f55scXaPhQ0hovYDrz0UTec0KXu4nubN
"""

# Example 14: NumPy - Unique Elements and Counting
import numpy as np

# Creating an array with duplicate values
array = np.array([1, 2, 2, 3, 4, 4, 4, 5])

# Finding unique elements and their counts
unique_elements, counts = np.unique(array, return_counts=True)

print('Unique Elements:', unique_elements)
print('Counts of Unique Elements:', counts)