# -*- coding: utf-8 -*-
"""Numpy_ModifyingArrayValues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 10: NumPy - Modifying Array Values using Indexing
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Modifying values at specific indices
array[[1, 3]] = [100, 200]

print('Modified Array:', array)