# -*- coding: utf-8 -*-
"""Numpy_Sorting Arrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 10: NumPy - Sorting Arrays
import numpy as np

# Creating an array
array = np.array([3, 1, 2, 5, 4])

# Sorting the array
sorted_array = np.sort(array)

print('Original Array:', array)
print('Sorted Array:', sorted_array)