# -*- coding: utf-8 -*-
"""Numpy_BasicArithmeticOperations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 2: NumPy - Basic Arithmetic Operations
import numpy as np

# Creating arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Arithmetic operations
added = np.add(array1, array2)
subtracted = np.subtract(array1, array2)
multiplied = np.multiply(array1, array2)
divided = np.divide(array1, array2)

print('Added:', added)
print('Subtracted:', subtracted)
print('Multiplied:', multiplied)
print('Divided:', divided)