# -*- coding: utf-8 -*-
"""Numpy_ReverseArrayUsingindexing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 21: NumPy - Reverse Array using Indexing
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Reversing the array using slicing
reversed_array = array[::-1]

print('Reversed Array:', reversed_array)