# -*- coding: utf-8 -*-
"""numpy_StatisticalFunctions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVoYGbEOO2SCY8FC5TIxYSQKbwjhTOpE
"""

# Example 13: NumPy - Statistical Functions
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5])

# Calculating statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print('Mean:', mean)
print('Median:', median)
print('Standard Deviation:', std_dev)
print('Variance:', variance)