# -*- coding: utf-8 -*-
"""Numpy_TransposingArrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bdPd_xsFDoJ6whuRijSh1dV73XY83o6c

# Example 8: Numpy - Transposing Arrays
"""

import numpy as np
array=np.array([[1,2], [3,4]]) #creating a 2D Array
transposed_array=np.transpose(array) # Transposing the array
print('Original Array:/n', array)
print('Transposed Array:/n', transposed_array)