# -*- coding: utf-8 -*-
"""Numpy_ExtractDiagonalElements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 16: NumPy - Extracting Diagonal Elements
import numpy as np

# Creating a square matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extracting the main diagonal
diagonal_elements = np.diag(matrix)

print('Diagonal Elements:', diagonal_elements)