# -*- coding: utf-8 -*-
"""Numpy_powerAndSquareRoot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 3: NumPy - Power and Square Root
import numpy as np

# Creating an array
array = np.array([1, 4, 9, 16])

# Power and square root
squared = np.power(array, 2)
sqrt = np.sqrt(array)

print('Squared Array:', squared)
print('Square Root of Array:', sqrt)