# -*- coding: utf-8 -*-
"""Numpy_ConcatenationOfArrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 15: NumPy - Concatenation of Arrays
import numpy as np

# Creating arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenating arrays
concatenated_array = np.concatenate((array1, array2))

print('Concatenated Array:', concatenated_array)