# -*- coding: utf-8 -*-
"""Numpy_SlicingWithStep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 5: NumPy - Slicing with Step
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Slicing with a step
step_slice = array[::2]  # Every second element

print('Sliced Array with Step 2:', step_slice)