# -*- coding: utf-8 -*-
"""Numpy_Brpadcasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 9: NumPy - Broadcasting
import numpy as np

# Creating an array
array = np.array([1, 2, 3])

# Broadcasting: Adding a scalar to an array
result = array + 10

print('Original Array:', array)
print('Array after Broadcasting:', result)