# -*- coding: utf-8 -*-
"""Numpy_ExponentialAndLogarithmicFunctions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 4: NumPy - Exponential and Logarithmic Functions
import numpy as np

# Creating an array
array = np.array([1, 2, 3])

# Exponential and logarithmic functions
exp_array = np.exp(array)
log_array = np.log(array)

print('Exponential of Array:', exp_array)
print('Logarithm of Array:', log_array)