# -*- coding: utf-8 -*-
"""Numpy_FancyIndexing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 4: NumPy - Fancy Indexing
import numpy as np

# Creating an array
array = np.array([10, 20, 30, 40, 50])

# Selecting specific indices
selected_elements = array[[1, 3, 4]]

print('Selected Elements:', selected_elements)