# -*- coding: utf-8 -*-
"""Numpy_LinearSpaceArray.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7GSmXVdxZPLqC3euFFUpbXAIAFrZHRk
"""

# Example 17: NumPy - Linear Space Array
import numpy as np

# Generating a linear space array with evenly spaced values
linear_space = np.linspace(0, 10, 5)

print('Linear Space Array:', linear_space)