# -*- coding: utf-8 -*-
"""Numpy_SplittingArrays.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kOwiheeJLsvEaWCBi0SsysxUC4BzGaz
"""

# Example 16: NumPy - Splitting Arrays
import numpy as np

# Creating an array
array = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into three parts
split_arrays = np.array_split(array, 3)

print('Split Arrays:', split_arrays)